# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a55fe3ee479174b0643d4411b196597e1b8017aa8b1ea67fb93e30e540518792120c4f3c1d95f7c542dfbdcc03f9282980337d22c037fa4fdfa6e5425646f69

test:
  secret_key_base: d76da502338a0190420a27d0c8f5f5e61518b5dc44e4863c8f924277cd178c09c4b40b2d6eb986f12a99ee83b0781682af9052face3734cf732525ca1d7f61fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
